### ISSUE TITLE
Improve the package with a story class

### ISSUE THREAD

**Issue by md-weber** [essarn/storyblok_client#10]
We could provide a class for a story. It seems that a story always consists of the following parameters.

```dart
  String name;
  DateTime createdAt;
  DateTime publishedAt;
  List alternates;
  int id;
  int uuid;
  Map<String, dynamic> content;
  String slug;
  String fullSlug;
  dynamic sortByDate;
  int position;
  List tagList;
  bool isStartPage;
  int parentId;
  dynamic metaData;
  String groupId;
  DateTime firstPublishedAt;
  String releasedId;
  String lang;
  String path;
  List translatedSlugs;
```

It would be great if we would implement that with the JsonSerializer

**Comment by essarn** [comment]
Great idea and should be added for sure. 

We should use the official docs as reference here: https://www.storyblok.com/docs/api/content-delivery#core-resources/stories/the-story-object
