### ISSUE TITLE
Setup a better folder structure instead of single file

### ISSUE THREAD

**Issue by md-weber** [essarn/storyblok_client#11]
I would suggest that we create a single file that exports all members.

As an example, I would relate to the provider package — a library file with an src folder and multiple files inside.

```dart
library provider;

export 'src/async_provider.dart';
export 'src/change_notifier_provider.dart';
export 'src/consumer.dart';
export 'src/listenable_provider.dart';
export 'src/provider.dart';
export 'src/proxy_provider.dart';
export 'src/selector.dart';
export 'src/value_listenable_provider.dart';
```

https://github.com/rrousselGit/provider/tree/master/lib

**Comment by essarn** [comment]
I have seen this pattern in a number of packages and considered it. If the package would be refactored should this be done with #10
