### ISSUE TITLE
[BUG] Problem with the assertions

### ISSUE THREAD

**Issue by md-weber** [essarn/storyblok_client#2]
If I only provide the full slug, with the assertions of the fetchOne fail.

```
    assert(fullSlug != null && id != null && uuid != null);
    assert(fullSlug != null || (id == null && uuid == null));
    assert(id != null || (fullSlug == null && uuid == null));
    assert(uuid != null || (fullSlug == null && id == null));
```

If I remove all of these asserts the result is correct.

Flutter Doctor
Channel Master
Dart 2.8.0

**Comment by essarn** [comment]
Solved with #3

**Comment by md-weber** [comment]
There happend an issue I think :) the branch was way too much. I just took it for a short scout, now all the files have moved and generated, we should maybe consider reverting it.

**Comment by essarn** [comment]
No need to revert the PR, the package is a good idea and I finished the setup and fixed some lints with  https://github.com/essarn/storyblok_client/commit/09fce85e200df12f2dc321cc5268b20c2e2b1253
