### ISSUE TITLE
Considering using published per default

### ISSUE THREAD

**Issue by md-weber** [essarn/storyblok_client#8]
According to the documentation of Storyblok, we could also use the published as default for the fetchOne and fetchMultiple.

> version | Default: published. Possible values: draft, published

https://www.storyblok.com/docs/api/content-delivery#core-resources/stories/retrieve-multiple-stories

**Comment by essarn** [comment]
I think it's fine to only add the `version` parameter to the request if one is explicitly provided, because this is already the same as the default behavior.
